[app]
    project_name = "My app"
    version = "1.0.0"
    debug = true
    cors_allowed_origins = "http://127.0.0.1:8000"

[database]
    db_path = "db/app.db"

[token]
    secret_key = "goida"
    algorithm = "HS256"
    token_expire_seconds = 3000000